* ------------------------------------------------------------------------------------------------------------------- *
*                                                                                                          /)_        *
*                                                                                                         //\  `.     *
*                                                                                                  ____,.//, \   \    *
*                           This file was generated by MAiNGO v0.6.0                            _.-'         `.`.  \   *
*                                                                                            ,'               : `..\  *
*                                                                                           :         ___      :      *
* Copyright (c) 2019 Process Systems Engineering (AVT.SVT), RWTH Aachen University         :       .'     `.    :     *
*                                                                                         :         `.    /     ;     *
* MAiNGO and the accompanying materials are made available under the                     :           /   /     ;      *
* terms of the Eclipse Public License 2.0 which is available at                         :        __.'   /     :       *
* http://www.eclipse.org/legal/epl-2.0.                                                 ;      /       /     :        *
*                                                                                       ;      `------'     /         *
* SPDX-License-Identifier: EPL-2.0                                                      :                  :          *
* Authors: Dominik Bongartz, Jaromil Najman, Susanne Sass, Alexander Mitsos             \                 /           *
*                                                                                        `.             .`            *
* Please provide all feedback and bugs to the developers.                                  '-._     _.-'              *
* E-mail: MAiNGO@avt.rwth-aachen.de                                                            `'''`                  *
* ------------------------------------------------------------------------------------------------------------------- *

*Continuous variables
variables input_0, input_1, TransformedInput_0, TransformedInput_1, accNeuronValue_0, accNeuronValue_1, accNeuronValue_2, accNeuronValue_3, accNeuronValue_4, accNeuronValue_5, accNeuronValue_6, accNeuronValue_7, accNeuronValue_8,
          accNeuronValue_9, accNeuronValue_10, accNeuronValue_11, accNeuronValue_12, accNeuronValue_13, accNeuronValue_14, accNeuronValue_15, accNeuronValue_16, accNeuronValue_17, accNeuronValue_18, accNeuronValue_19,
          accNeuronValue_20, accNeuronValue_21, accNeuronValue_22, accNeuronValue_23, accNeuronValue_24, accNeuronValue_25, accNeuronValue_26, accNeuronValue_27, accNeuronValue_28, accNeuronValue_29,
          accNeuronValue_30, accNeuronValue_31, accNeuronValue_32, accNeuronValue_33, accNeuronValue_34, accNeuronValue_35, accNeuronValue_36, accNeuronValue_37, accNeuronValue_38, accNeuronValue_39,
          accNeuronValue_40, accNeuronValue_41, accNeuronValue_42, accNeuronValue_43, accNeuronValue_44, accNeuronValue_45, accNeuronValue_46, accNeuronValue_47, neuronValue_0, neuronValue_1,
          neuronValue_2, neuronValue_3, neuronValue_4, neuronValue_5, neuronValue_6, neuronValue_7, neuronValue_8, neuronValue_9, neuronValue_10, neuronValue_11, neuronValue_12, neuronValue_13,
          neuronValue_14, neuronValue_15, neuronValue_16, neuronValue_17, neuronValue_18, neuronValue_19, neuronValue_20, neuronValue_21, neuronValue_22, neuronValue_23, neuronValue_24, neuronValue_25,
          neuronValue_26, neuronValue_27, neuronValue_28, neuronValue_29, neuronValue_30, neuronValue_31, neuronValue_32, neuronValue_33, neuronValue_34, neuronValue_35, neuronValue_36, neuronValue_37,
          neuronValue_38, neuronValue_39, neuronValue_40, neuronValue_41, neuronValue_42, neuronValue_43, neuronValue_44, neuronValue_45, neuronValue_46, neuronValue_47, output_0, objectiveVar;

*Continuous variable bounds
input_0.LO = -3;
input_0.UP = 3;
input_1.LO = -3;
input_1.UP = 3;
TransformedInput_0.LO = -2;
TransformedInput_0.UP = 2;
TransformedInput_1.LO = -2;
TransformedInput_1.UP = 2;
accNeuronValue_0.LO = -1000000;
accNeuronValue_0.UP = 1000000;
accNeuronValue_1.LO = -1000000;
accNeuronValue_1.UP = 1000000;
accNeuronValue_2.LO = -1000000;
accNeuronValue_2.UP = 1000000;
accNeuronValue_3.LO = -1000000;
accNeuronValue_3.UP = 1000000;
accNeuronValue_4.LO = -1000000;
accNeuronValue_4.UP = 1000000;
accNeuronValue_5.LO = -1000000;
accNeuronValue_5.UP = 1000000;
accNeuronValue_6.LO = -1000000;
accNeuronValue_6.UP = 1000000;
accNeuronValue_7.LO = -1000000;
accNeuronValue_7.UP = 1000000;
accNeuronValue_8.LO = -1000000;
accNeuronValue_8.UP = 1000000;
accNeuronValue_9.LO = -1000000;
accNeuronValue_9.UP = 1000000;
accNeuronValue_10.LO = -1000000;
accNeuronValue_10.UP = 1000000;
accNeuronValue_11.LO = -1000000;
accNeuronValue_11.UP = 1000000;
accNeuronValue_12.LO = -1000000;
accNeuronValue_12.UP = 1000000;
accNeuronValue_13.LO = -1000000;
accNeuronValue_13.UP = 1000000;
accNeuronValue_14.LO = -1000000;
accNeuronValue_14.UP = 1000000;
accNeuronValue_15.LO = -1000000;
accNeuronValue_15.UP = 1000000;
accNeuronValue_16.LO = -1000000;
accNeuronValue_16.UP = 1000000;
accNeuronValue_17.LO = -1000000;
accNeuronValue_17.UP = 1000000;
accNeuronValue_18.LO = -1000000;
accNeuronValue_18.UP = 1000000;
accNeuronValue_19.LO = -1000000;
accNeuronValue_19.UP = 1000000;
accNeuronValue_20.LO = -1000000;
accNeuronValue_20.UP = 1000000;
accNeuronValue_21.LO = -1000000;
accNeuronValue_21.UP = 1000000;
accNeuronValue_22.LO = -1000000;
accNeuronValue_22.UP = 1000000;
accNeuronValue_23.LO = -1000000;
accNeuronValue_23.UP = 1000000;
accNeuronValue_24.LO = -1000000;
accNeuronValue_24.UP = 1000000;
accNeuronValue_25.LO = -1000000;
accNeuronValue_25.UP = 1000000;
accNeuronValue_26.LO = -1000000;
accNeuronValue_26.UP = 1000000;
accNeuronValue_27.LO = -1000000;
accNeuronValue_27.UP = 1000000;
accNeuronValue_28.LO = -1000000;
accNeuronValue_28.UP = 1000000;
accNeuronValue_29.LO = -1000000;
accNeuronValue_29.UP = 1000000;
accNeuronValue_30.LO = -1000000;
accNeuronValue_30.UP = 1000000;
accNeuronValue_31.LO = -1000000;
accNeuronValue_31.UP = 1000000;
accNeuronValue_32.LO = -1000000;
accNeuronValue_32.UP = 1000000;
accNeuronValue_33.LO = -1000000;
accNeuronValue_33.UP = 1000000;
accNeuronValue_34.LO = -1000000;
accNeuronValue_34.UP = 1000000;
accNeuronValue_35.LO = -1000000;
accNeuronValue_35.UP = 1000000;
accNeuronValue_36.LO = -1000000;
accNeuronValue_36.UP = 1000000;
accNeuronValue_37.LO = -1000000;
accNeuronValue_37.UP = 1000000;
accNeuronValue_38.LO = -1000000;
accNeuronValue_38.UP = 1000000;
accNeuronValue_39.LO = -1000000;
accNeuronValue_39.UP = 1000000;
accNeuronValue_40.LO = -1000000;
accNeuronValue_40.UP = 1000000;
accNeuronValue_41.LO = -1000000;
accNeuronValue_41.UP = 1000000;
accNeuronValue_42.LO = -1000000;
accNeuronValue_42.UP = 1000000;
accNeuronValue_43.LO = -1000000;
accNeuronValue_43.UP = 1000000;
accNeuronValue_44.LO = -1000000;
accNeuronValue_44.UP = 1000000;
accNeuronValue_45.LO = -1000000;
accNeuronValue_45.UP = 1000000;
accNeuronValue_46.LO = -1000000;
accNeuronValue_46.UP = 1000000;
accNeuronValue_47.LO = -1000000;
accNeuronValue_47.UP = 1000000;
neuronValue_0.LO = -2;
neuronValue_0.UP = 2;
neuronValue_1.LO = -2;
neuronValue_1.UP = 2;
neuronValue_2.LO = -2;
neuronValue_2.UP = 2;
neuronValue_3.LO = -2;
neuronValue_3.UP = 2;
neuronValue_4.LO = -2;
neuronValue_4.UP = 2;
neuronValue_5.LO = -2;
neuronValue_5.UP = 2;
neuronValue_6.LO = -2;
neuronValue_6.UP = 2;
neuronValue_7.LO = -2;
neuronValue_7.UP = 2;
neuronValue_8.LO = -2;
neuronValue_8.UP = 2;
neuronValue_9.LO = -2;
neuronValue_9.UP = 2;
neuronValue_10.LO = -2;
neuronValue_10.UP = 2;
neuronValue_11.LO = -2;
neuronValue_11.UP = 2;
neuronValue_12.LO = -2;
neuronValue_12.UP = 2;
neuronValue_13.LO = -2;
neuronValue_13.UP = 2;
neuronValue_14.LO = -2;
neuronValue_14.UP = 2;
neuronValue_15.LO = -2;
neuronValue_15.UP = 2;
neuronValue_16.LO = -2;
neuronValue_16.UP = 2;
neuronValue_17.LO = -2;
neuronValue_17.UP = 2;
neuronValue_18.LO = -2;
neuronValue_18.UP = 2;
neuronValue_19.LO = -2;
neuronValue_19.UP = 2;
neuronValue_20.LO = -2;
neuronValue_20.UP = 2;
neuronValue_21.LO = -2;
neuronValue_21.UP = 2;
neuronValue_22.LO = -2;
neuronValue_22.UP = 2;
neuronValue_23.LO = -2;
neuronValue_23.UP = 2;
neuronValue_24.LO = -2;
neuronValue_24.UP = 2;
neuronValue_25.LO = -2;
neuronValue_25.UP = 2;
neuronValue_26.LO = -2;
neuronValue_26.UP = 2;
neuronValue_27.LO = -2;
neuronValue_27.UP = 2;
neuronValue_28.LO = -2;
neuronValue_28.UP = 2;
neuronValue_29.LO = -2;
neuronValue_29.UP = 2;
neuronValue_30.LO = -2;
neuronValue_30.UP = 2;
neuronValue_31.LO = -2;
neuronValue_31.UP = 2;
neuronValue_32.LO = -2;
neuronValue_32.UP = 2;
neuronValue_33.LO = -2;
neuronValue_33.UP = 2;
neuronValue_34.LO = -2;
neuronValue_34.UP = 2;
neuronValue_35.LO = -2;
neuronValue_35.UP = 2;
neuronValue_36.LO = -2;
neuronValue_36.UP = 2;
neuronValue_37.LO = -2;
neuronValue_37.UP = 2;
neuronValue_38.LO = -2;
neuronValue_38.UP = 2;
neuronValue_39.LO = -2;
neuronValue_39.UP = 2;
neuronValue_40.LO = -2;
neuronValue_40.UP = 2;
neuronValue_41.LO = -2;
neuronValue_41.UP = 2;
neuronValue_42.LO = -2;
neuronValue_42.UP = 2;
neuronValue_43.LO = -2;
neuronValue_43.UP = 2;
neuronValue_44.LO = -2;
neuronValue_44.UP = 2;
neuronValue_45.LO = -2;
neuronValue_45.UP = 2;
neuronValue_46.LO = -2;
neuronValue_46.UP = 2;
neuronValue_47.LO = -2;
neuronValue_47.UP = 2;
output_0.LO = -1000000;
output_0.UP = 1000000;

*Equation variables
equations objective, 
eq1,
eq2,
eq3,
eq4,
eq5,
eq6,
eq7,
eq8,
eq9,
eq10,
eq11,
eq12,
eq13,
eq14,
eq15,
eq16,
eq17,
eq18,
eq19,
eq20,
eq21,
eq22,
eq23,
eq24,
eq25,
eq26,
eq27,
eq28,
eq29,
eq30,
eq31,
eq32,
eq33,
eq34,
eq35,
eq36,
eq37,
eq38,
eq39,
eq40,
eq41,
eq42,
eq43,
eq44,
eq45,
eq46,
eq47,
eq48,
eq49,
eq50,
eq51,
eq52,
eq53,
eq54,
eq55,
eq56,
eq57,
eq58,
eq59,
eq60,
eq61,
eq62,
eq63,
eq64,
eq65,
eq66,
eq67,
eq68,
eq69,
eq70,
eq71,
eq72,
eq73,
eq74,
eq75,
eq76,
eq77,
eq78,
eq79,
eq80,
eq81,
eq82,
eq83,
eq84,
eq85,
eq86,
eq87,
eq88,
eq89,
eq90,
eq91,
eq92,
eq93,
eq94,
eq95,
eq96,
eq97,
eq98,
eq99;

*Objective function
objective .. objectiveVar =E= output_0;

*Equalities
eq1 .. TransformedInput_0-((input_0+2.9933)*0.1669644198821231*2-1) =E= 0;
eq2 .. TransformedInput_1-((input_1+2.9881)*0.1672940192388122*2-1) =E= 0;
eq3 .. accNeuronValue_0-(TransformedInput_0*9.106999999999999+TransformedInput_1*2.9434)+9.6302 =E= 0;
eq4 .. tanh(accNeuronValue_0)-neuronValue_0 =E= 0;
eq5 .. accNeuronValue_1+TransformedInput_0*6.931-(TransformedInput_1*3.752)-7.3102 =E= 0;
eq6 .. tanh(accNeuronValue_1)-neuronValue_1 =E= 0;
eq7 .. accNeuronValue_2+TransformedInput_0*3.3643+TransformedInput_1*0.82526-2.982 =E= 0;
eq8 .. tanh(accNeuronValue_2)-neuronValue_2 =E= 0;
eq9 .. accNeuronValue_3+TransformedInput_0*1.6419+TransformedInput_1*4.4852-2.7724 =E= 0;
eq10 .. tanh(accNeuronValue_3)-neuronValue_3 =E= 0;
eq11 .. accNeuronValue_4-(TransformedInput_0*0.0022644-TransformedInput_1*4.8678)+4.425 =E= 0;
eq12 .. tanh(accNeuronValue_4)-neuronValue_4 =E= 0;
eq13 .. accNeuronValue_5+TransformedInput_0*7.1986+TransformedInput_1*1.879-6.2578 =E= 0;
eq14 .. tanh(accNeuronValue_5)-neuronValue_5 =E= 0;
eq15 .. accNeuronValue_6-(TransformedInput_0*0.7481100000000001-TransformedInput_1*4.2019)+2.6263 =E= 0;
eq16 .. tanh(accNeuronValue_6)-neuronValue_6 =E= 0;
eq17 .. accNeuronValue_7+TransformedInput_0*2.6532+TransformedInput_1*2.1972-1.6024 =E= 0;
eq18 .. tanh(accNeuronValue_7)-neuronValue_7 =E= 0;
eq19 .. accNeuronValue_8+TransformedInput_0*1.959+TransformedInput_1*6.615+3.2137 =E= 0;
eq20 .. tanh(accNeuronValue_8)-neuronValue_8 =E= 0;
eq21 .. accNeuronValue_9+TransformedInput_0*0.97646+TransformedInput_1*5.4722+3.4351 =E= 0;
eq22 .. tanh(accNeuronValue_9)-neuronValue_9 =E= 0;
eq23 .. accNeuronValue_10+TransformedInput_0*9.0563-(TransformedInput_1*0.86075)-6.8078 =E= 0;
eq24 .. tanh(accNeuronValue_10)-neuronValue_10 =E= 0;
eq25 .. accNeuronValue_11+TransformedInput_0*2.517-(TransformedInput_1*1.1233)-1.4607 =E= 0;
eq26 .. tanh(accNeuronValue_11)-neuronValue_11 =E= 0;
eq27 .. accNeuronValue_12+TransformedInput_0*2.5326-(TransformedInput_1*2.8312)-2.0091 =E= 0;
eq28 .. tanh(accNeuronValue_12)-neuronValue_12 =E= 0;
eq29 .. accNeuronValue_13+TransformedInput_0*1.6402-(TransformedInput_1*6.7132)-2.3059 =E= 0;
eq30 .. tanh(accNeuronValue_13)-neuronValue_13 =E= 0;
eq31 .. accNeuronValue_14+TransformedInput_0*1.7874-(TransformedInput_1*3.6828)-1.3993 =E= 0;
eq32 .. tanh(accNeuronValue_14)-neuronValue_14 =E= 0;
eq33 .. accNeuronValue_15+TransformedInput_0*4.222-(TransformedInput_1*0.39648)-0.96421 =E= 0;
eq34 .. tanh(accNeuronValue_15)-neuronValue_15 =E= 0;
eq35 .. accNeuronValue_16+TransformedInput_0*2.4124-(TransformedInput_1*8.809200000000001)-4.2313 =E= 0;
eq36 .. tanh(accNeuronValue_16)-neuronValue_16 =E= 0;
eq37 .. accNeuronValue_17-(TransformedInput_0*0.44292+TransformedInput_1*5.2802)-2.0424 =E= 0;
eq38 .. tanh(accNeuronValue_17)-neuronValue_17 =E= 0;
eq39 .. accNeuronValue_18+TransformedInput_0*3.5181-(TransformedInput_1*1.3028)-0.06515600000000001 =E= 0;
eq40 .. tanh(accNeuronValue_18)-neuronValue_18 =E= 0;
eq41 .. accNeuronValue_19-(TransformedInput_0*0.11321-TransformedInput_1*4.7232)+0.85321 =E= 0;
eq42 .. tanh(accNeuronValue_19)-neuronValue_19 =E= 0;
eq43 .. accNeuronValue_20+TransformedInput_0*3.9567+TransformedInput_1*1.2763-0.8144400000000001 =E= 0;
eq44 .. tanh(accNeuronValue_20)-neuronValue_20 =E= 0;
eq45 .. accNeuronValue_21+TransformedInput_0*4.7696+TransformedInput_1*0.77349+0.11125 =E= 0;
eq46 .. tanh(accNeuronValue_21)-neuronValue_21 =E= 0;
eq47 .. accNeuronValue_22+TransformedInput_0*2.0503-(TransformedInput_1*2.5098)-0.082049 =E= 0;
eq48 .. tanh(accNeuronValue_22)-neuronValue_22 =E= 0;
eq49 .. accNeuronValue_23+TransformedInput_0*3.6665+TransformedInput_1*2.3889+0.89139 =E= 0;
eq50 .. tanh(accNeuronValue_23)-neuronValue_23 =E= 0;
eq51 .. accNeuronValue_24+TransformedInput_0*3.28-(TransformedInput_1*2.5905)+0.73939 =E= 0;
eq52 .. tanh(accNeuronValue_24)-neuronValue_24 =E= 0;
eq53 .. accNeuronValue_25+TransformedInput_0*1.6153+TransformedInput_1*2.3342-0.87185 =E= 0;
eq54 .. tanh(accNeuronValue_25)-neuronValue_25 =E= 0;
eq55 .. accNeuronValue_26-(TransformedInput_0*1.1136+TransformedInput_1*5.306)+1.007 =E= 0;
eq56 .. tanh(accNeuronValue_26)-neuronValue_26 =E= 0;
eq57 .. accNeuronValue_27-(TransformedInput_0*2.924+TransformedInput_1*2.8961)+0.23247 =E= 0;
eq58 .. tanh(accNeuronValue_27)-neuronValue_27 =E= 0;
eq59 .. accNeuronValue_28-(TransformedInput_0*1.8187-TransformedInput_1*7.3381)-2.5414 =E= 0;
eq60 .. tanh(accNeuronValue_28)-neuronValue_28 =E= 0;
eq61 .. accNeuronValue_29+TransformedInput_0*3.1054+TransformedInput_1*2.1262+0.6871699999999999 =E= 0;
eq62 .. tanh(accNeuronValue_29)-neuronValue_29 =E= 0;
eq63 .. accNeuronValue_30+TransformedInput_0*1.7447+TransformedInput_1*4.9528+2.1755 =E= 0;
eq64 .. tanh(accNeuronValue_30)-neuronValue_30 =E= 0;
eq65 .. accNeuronValue_31-(TransformedInput_0*2.6515-TransformedInput_1*4.3827)-1.5304 =E= 0;
eq66 .. tanh(accNeuronValue_31)-neuronValue_31 =E= 0;
eq67 .. accNeuronValue_32+TransformedInput_0*4.1487+TransformedInput_1*1.3684+2.0242 =E= 0;
eq68 .. tanh(accNeuronValue_32)-neuronValue_32 =E= 0;
eq69 .. accNeuronValue_33+TransformedInput_0*3.7103-(TransformedInput_1*0.24032)+0.90212 =E= 0;
eq70 .. tanh(accNeuronValue_33)-neuronValue_33 =E= 0;
eq71 .. accNeuronValue_34+TransformedInput_0*0.13686+TransformedInput_1*6.2284-2.2225 =E= 0;
eq72 .. tanh(accNeuronValue_34)-neuronValue_34 =E= 0;
eq73 .. accNeuronValue_35-(TransformedInput_0*2.2927-TransformedInput_1*9.492800000000001)-4.6145 =E= 0;
eq74 .. tanh(accNeuronValue_35)-neuronValue_35 =E= 0;
eq75 .. accNeuronValue_36-(TransformedInput_0*3.294+TransformedInput_1*4.2287)-2.6502 =E= 0;
eq76 .. tanh(accNeuronValue_36)-neuronValue_36 =E= 0;
eq77 .. accNeuronValue_37+TransformedInput_0*0.23662+TransformedInput_1*6.3228-4.1002 =E= 0;
eq78 .. tanh(accNeuronValue_37)-neuronValue_37 =E= 0;
eq79 .. accNeuronValue_38-(TransformedInput_0*3.5074-TransformedInput_1*1.5242)-1.813 =E= 0;
eq80 .. tanh(accNeuronValue_38)-neuronValue_38 =E= 0;
eq81 .. accNeuronValue_39-(TransformedInput_0*3.8242-TransformedInput_1*3.1234)-3.6466 =E= 0;
eq82 .. tanh(accNeuronValue_39)-neuronValue_39 =E= 0;
eq83 .. accNeuronValue_40-(TransformedInput_0*3.6691-TransformedInput_1*0.31999)-2.8962 =E= 0;
eq84 .. tanh(accNeuronValue_40)-neuronValue_40 =E= 0;
eq85 .. accNeuronValue_41-(TransformedInput_0*8.182399999999999+TransformedInput_1*4.0193)-7.1904 =E= 0;
eq86 .. tanh(accNeuronValue_41)-neuronValue_41 =E= 0;
eq87 .. accNeuronValue_42+TransformedInput_0*2.4545-(TransformedInput_1*4.0042)+2.8117 =E= 0;
eq88 .. tanh(accNeuronValue_42)-neuronValue_42 =E= 0;
eq89 .. accNeuronValue_43+TransformedInput_0*6.44+TransformedInput_1*8.0741+6.5173 =E= 0;
eq90 .. tanh(accNeuronValue_43)-neuronValue_43 =E= 0;
eq91 .. accNeuronValue_44-(TransformedInput_0*4.285-TransformedInput_1*8.051600000000001)-9.227600000000001 =E= 0;
eq92 .. tanh(accNeuronValue_44)-neuronValue_44 =E= 0;
eq93 .. accNeuronValue_45+TransformedInput_0*4.5291-(TransformedInput_1*8.4581)+9.7143 =E= 0;
eq94 .. tanh(accNeuronValue_45)-neuronValue_45 =E= 0;
eq95 .. accNeuronValue_46+TransformedInput_0*9.029999999999999+TransformedInput_1*5.8701+8.543699999999999 =E= 0;
eq96 .. tanh(accNeuronValue_46)-neuronValue_46 =E= 0;
eq97 .. accNeuronValue_47+neuronValue_0*0.065704-(neuronValue_1*0.033719)+neuronValue_2*0.76133-(neuronValue_3*0.48805)+neuronValue_4*0.10716-(neuronValue_5*0.12256)-(neuronValue_6*0.47773)-(neuronValue_7*1.4593)-(neuronValue_8*0.12829)-(neuronValue_9*0.17066)+neuronValue_10*0.031784-(neuronValue_11*1.0343)+neuronValue_12*0.7514999999999999-(neuronValue_13*0.17572)-(neuronValue_14*0.89455)+neuronValue_15*1.0327-(neuronValue_16*0.053874)-(neuronValue_17*0.32397)-(neuronValue_18*1.8663)-(neuronValue_19*0.5493)+neuronValue_20*0.60609-(neuronValue_21*0.40068)+neuronValue_22*0.92391+neuronValue_23*0.93709+neuronValue_24*0.24686+neuronValue_25*1.7127+neuronValue_26*0.30011+neuronValue_27*0.28025+neuronValue_28*0.23534-(neuronValue_29*1.205)+neuronValue_30*0.50945+neuronValue_31*0.20317-(neuronValue_32*0.26555)+neuronValue_33*1.6129+neuronValue_34*0.28066+neuronValue_35*0.080875+neuronValue_36*0.26354-(neuronValue_37*0.17364)+neuronValue_38*0.58227+neuronValue_39*0.15634-(neuronValue_40*0.20363)-(neuronValue_41*0.041905)+neuronValue_42*0.43558-(neuronValue_43*0.031562)+neuronValue_44*1.0758+neuronValue_45*0.96224-(neuronValue_46*0.042862)+0.060465 =E= 0;
eq98 .. accNeuronValue_47-neuronValue_47 =E= 0;
eq99 .. output_0-((neuronValue_47+1)*0.5*13.94-6.2098) =E= 0;

*Model information and options
model m / all /;

*Optional option file
m.optfile = 1;

*Optimality tolerances, time and solver
option OPTCA = 0.01;
option OPTCR = 0.01;
option RESLIM = 86400;
option NLP = SCIP;

*Solve statement
solve m using NLP minimizing objectiveVar;